image: dtsdwarak/ruby-nodejs:latest

pages:
  stage: deploy
  script:
  - npm install
  - npm install -g gulp
  - bundle install
  - bundle update
  - gem install jekyll -v 3.8.5
  - gulp release
  artifacts:
    paths:
    - public
  only:
  - master
