# Permalinks
permalink:           pretty
future: true

# Markdown syntax
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  line_numbers: true

# Setup
title:               Dwarak
tagline:             'Code. Life. Fun.'
description:         'is a i-really-want-to-be-a-guitarist guy. Loves Gadgets, geeks and girls. Is an engineer by profession and blogger by passion.'
url:                 https://blog.dwarak.in
baseurl:             ''
timezone:            'Asia/Kolkata'

# About/contact
author:
  name:              Dwaraka Nath
  url:               https://twitter.com/dtsdwarak
  email:             me@dwarak.in

# Custom vars
version:             1.0.1

# Enforce SSL
enforce_ssl: blog.dwarak.in
